### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by seb-thomas** [spoeken/generator-craftcms#7]
Hey thanks for this great generator, it's been useful! It was so seamless infact, that I forgot I was using it and spent maybe an hour changing perms and that kind of thing until I realised I was using this!

As you say to use `/app` in dev, and `/public` in production, how you do get image assets during dev?

I get a 404 for any images I've uploaded, because the site config uses '/public', and MAMP serves from '/app'. How do you get around this when you use your generator? Do you have specific config settings?

Thanks!

**Comment by spoeken** [comment]
Hi there. Glad to hear someone else is actually using this :) 
This is something I haven't though about, I rarely use the same images in dev as I do in production, and when I do I find it easier to use an S3 bucket.

Let me see if I can find a solution.

**Comment by seb-thomas** [comment]
True, I should really set one of those up! For the time being I just check if it's on devMode and if so use placeholder images.

And yes, definitely using it :)

**Comment by spoeken** [comment]
Ok, a simple solution for now, I'm not sure if this is the best or if this is something the build task should handle.

first, backup your uploads folder somehow.
move the uploads folder from app/uploads to public/uploads
cd into app/ and make a symlink like this
ln -s ../public/uploads uploads
