### ISSUE TITLE
Can't get it to work...

### ISSUE THREAD

**Issue by josefarrugia** [spoeken/generator-craftcms#8]
Hi All,

I have been endlessly trying for the past few hours in getting the Yeoman package "generator-craftcms" working, however, I can't seem to get the asset files working properly (CSS and JS) files.

This is what I have achieved so far:
1. Yo in project folder
2. npm install gulp
3. bower install
4. npm install
5. gulp watch
6. gulp build

This is my current folder structure:
- /Applications/MAMP/htdocs/project_name
- /Applications/MAMP/htdocs/project_name/app
- /Applications/MAMP/htdocs/project_name/craft
- /Applications/MAMP/htdocs/project_name/public

Have I missed a step? Awaiting for some enlightenment.

J

**Comment by spoeken** [comment]
What error do you get when you run gulp watch?
And have you got the compass gem?
if not: `gem update --system` and `gem install compass`
